name: "Test against Cogent3 develop branch"

on:
    schedule:
      - cron: '0 21 * * *' # 7am AEST
    workflow_dispatch:  # support for manual triggering

jobs:
  cogent3-dev:
    name: "cogent3-dev"
    runs-on: ubuntu-latest
    if: github.repository == 'HuttleyLab/MutationDiseq'

    steps:
      - uses: "actions/checkout@v7"
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v10
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.12"

      - name: Install nox
        run: uv tool install nox

      - name: Run tests against the cogent3 develop branch
        run: nox -db uv -s test_dev
